Desktop version
username-forGithub/my_portfolio pull request #5
Opened 2022-07-07 14:31 UTC by username-forGithub

Added desktop version.

2022-07-07 14:59 UTC, zieeco requested changes
Hi @username-forGithub,


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-07 14:59 UTC, zieeco commented on css/style.css
> +@media (min-width: 767px) {
- Please, kindly use a media query not less than `768px` to meet the project requirement.

2022-07-07 14:59 UTC, zieeco commented on css/style.css
> +@media (min-width: 767px) {
- Please, kindly use a media query not less than `768px` to meet the project requirement.

2022-07-07 14:59 UTC, zieeco commented on css/style.css
> +@media (min-width: 767px) {
- Please, kindly use a media query not less than `768px` to meet the project requirement.

2022-07-07 14:59 UTC, zieeco commented on css/style.css
> +@media (min-width: 767px) {
- Please, kindly use a media query not less than `768px` to meet the project requirement.

2022-07-07 14:59 UTC, zieeco commented on css/style.css
>  @media (max-width: 575px) {
- Please, kindly use a media query not less than `768px` to meet the project requirement.

2022-07-07 14:59 UTC, zieeco commented on css/style.css
> +@media (min-width: 767px) {
- Please, kindly use a media query not less than `768px` to meet the project requirement.

2022-07-07 14:59 UTC, zieeco commented on css/style.css
> +@media (min-width: 767px) {
- Please, kindly use a media query not less than `768px` to meet the project requirement.

2022-07-07 14:59 UTC, zieeco commented on css/style.css
> +@media (max-width: 767px) {
- Please, kindly use a media query not less than `768px` to meet the project requirement.

2022-07-07 14:59 UTC, zieeco commented on index.html
> +        <img class="last" src="img/Frame.png" alt="">
- Please, kindly add the missign background image to match the Figma design below:

*figma*
![](https://user-images.githubusercontent.com/59397159/177803729-781b906d-6b03-4cbd-9406-9330f7c2e900.png)

*your design*
![](https://user-images.githubusercontent.com/59397159/177803742-b29b652e-a6da-4f05-83f2-41a308435496.png)

2022-07-07 17:49 UTC, username-forGithub commented on css/style.css
> +@media (min-width: 767px) {
Thanks. 
Changed.

2022-07-07 17:49 UTC, username-forGithub commented on css/style.css
> +@media (min-width: 767px) {
Thanks.
Changed.

2022-07-07 18:26 UTC, mirouhml requested changes
# REQUIRED CHANGES 🔴

Hi @username-forGithub, 

Great work on making the changes requested by the previous reviewer 👏 

You've done well implementing some of the requested changes, but there is still one that isn't addressed yet, but don't worry you're almost there!! 😉

![image](https://media3.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif?cid=ecf05e4734q298svfm6dye74pbw2yeu64ps29whho9qaoirw&rid=giphy.gif&ct=g)

 ## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-07 18:26 UTC, mirouhml commented on css/style.css
> +}
- [ ] Please know that because of these lines your background isn't visible for a width that's less than `1230px`, as you can see in this picture:

![image](https://user-images.githubusercontent.com/20567503/177842881-0cac210e-90c1-4262-a050-b6764a9b4e27.png)

Please change it so that it's visible on all desktop screens that are greater than 768. 😁

2022-07-08 07:59 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello  @username-forGithub        , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

[OPTIONAL] Kindly add a screenshot to your README file showing your webpage user Interface. You can use extentions like fireshot to capturer the entire page.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 08:01 UTC, merged